trigger:
  - master

jobs:
  - template: ci/azure-build-template.yml
    parameters:
      name: Linux
      vmImage: ubuntu-16.04

  - template: ci/azure-build-template.yml
    parameters:
      name: macOS
      vmImage: macOS-10.13

  - template: ci/azure-build-template.yml
    parameters:
      name: Windows
      vmImage: vs2017-win2016